In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('BIKE_DETAILS.csv')

In [3]:
data

name  selling_price  year seller_type  \
0               Royal Enfield Classic 350         175000  2019  Individual   
1                               Honda Dio          45000  2017  Individual   
2     Royal Enfield Classic Gunmetal Grey         150000  2018  Individual   
3       Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015  Individual   
4                   Yamaha SZ [2013-2014]          20000  2011  Individual   
...                                   ...            ...   ...         ...   
1056                            Activa 3g          17000  2010  Individual   
1057                     Honda CB twister          16000  2012  Individual   
1058                   Bajaj Discover 125          15000  2013  Individual   
1059                       Honda CB Shine          12000  2009  Individual   
1060                     Bajaj Pulsar 150          10000  2008  Individual   

          owner  km_driven  ex_showroom_price  
0     1st owner        350                NaN  
1     1st owner       5650                NaN  
2     1st owner      12000           148114.0  
3     1st owner      23000            89643.0  
4     2nd owner      21000                NaN  
...         ...        ...                ...  
1056  1st owner     500000            52000.0  
1057  1st owner      33000            51000.0  
1058  2nd owner      35000            57000.0  
1059  1st owner      53000            58000.0  
1060  1st owner      92233            75000.0  

[1061 rows x 7 columns]

In [4]:
data.shape

(1061, 7)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   name               1061 non-null   object 
 1   selling_price      1061 non-null   int64  
 2   year               1061 non-null   int64  
 3   seller_type        1061 non-null   object 
 4   owner              1061 non-null   object 
 5   km_driven          1061 non-null   int64  
 6   ex_showroom_price  626 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 58.1+ KB


In [6]:
data.isnull().sum()

name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64

In [7]:
# needed columns are selling_price, year, km_driven and name of the bike
data = data[['name', 'selling_price', 'year', 'km_driven']]

In [8]:
data

name  selling_price  year  km_driven
0               Royal Enfield Classic 350         175000  2019        350
1                               Honda Dio          45000  2017       5650
2     Royal Enfield Classic Gunmetal Grey         150000  2018      12000
3       Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015      23000
4                   Yamaha SZ [2013-2014]          20000  2011      21000
...                                   ...            ...   ...        ...
1056                            Activa 3g          17000  2010     500000
1057                     Honda CB twister          16000  2012      33000
1058                   Bajaj Discover 125          15000  2013      35000
1059                       Honda CB Shine          12000  2009      53000
1060                     Bajaj Pulsar 150          10000  2008      92233

[1061 rows x 4 columns]

In [9]:
data.dtypes

name             object
selling_price     int64
year              int64
km_driven         int64
dtype: object

In [10]:
data['selling_price'].unique()

array([175000,  45000, 150000,  65000,  20000,  18000,  78500, 180000,
        30000,  50000,  35000,  28000,  80000, 365000, 185000,  25000,
        40000, 120000,  15000,  26000,  32000, 110000,  42000,  21000,
        55000,  38000,  43000,  62000,  60000,  90000, 125000,  85000,
        29900,  70000,  48000,  34000, 165000,  29500,  95000,   7500,
       160000, 140000,  22000,  22989,  24999,  75000,  17500,  57000,
        83900, 135000, 299000, 750000, 190000, 130000,  54786,  72000,
       100000, 138000, 170000, 123000,  23000,  41000,  47999,  36999,
        12000,  27000,  10000,  56000,  58000,  87000, 145000,   9000,
        14000,  17000, 210000,  54000, 260000,  98000, 200000, 195000,
       270000, 425000, 760000,  37000, 330000, 162000, 285000,  69000,
       300000,  26500,  78000,   8000,  39000,  36000,  16000,  83299,
        14700,  19000,  14900,  24000,  24700,  52000,  47000, 105000,
       115000,   5000,  86000,  28700,   6000,  23500,  68000,  20100,
      

In [11]:
data['km_driven'].unique()

array([   350,   5650,  12000,  23000,  21000,  60000,  17000,  39000,
        32000,  42000,  10000,  21178,   1127,   1700,  55000,  27000,
        45000,  17450,  20696,   2000,  20000,  35000,  15210,  24000,
         2500,  75000,  50000,   6502,  16000,  13000,  12800,   4600,
        81000,   8000,  57000,  26000,  29000,  43000,  40000,   3000,
        80000,  30000,  41000,   8150,   1933,  55750,  15856,   3700,
        21938,  48000,  54000,  15000,   3500,   9000,  38000,  22000,
         9432,  70000, 500000,  30514, 130000,  25000,  22770,   6330,
          500,  43400,   7004,  16500,  12500,   9600,  11000,   7500,
       120000,   6465,  18803,   7000,   6100,  14000,  85000,  18000,
         1500,  90000,  36500,  49000,   8500,   3775,  14500,   4000,
        99000,  52000,   2300,  36000,  71000,  15888,   5600,  19612,
        33700, 100000,   6000,  46000,  72000,  67000,  15500,  60855,
        37714,  34601,  44000,  17500,   6500,   2200,  66191,  32800,
      

In [12]:
data['name'] = data['name'].str.split(' ').str.slice(0,3).str.join(' ')

C:\conda_tmp\ipykernel_15224\4132768251.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['name'] = data['name'].str.split(' ').str.slice(0,3).str.join(' ')


In [14]:
data = data.reset_index(drop=True)

In [15]:
data

name  selling_price  year  km_driven
0     Royal Enfield Classic         175000  2019        350
1                 Honda Dio          45000  2017       5650
2     Royal Enfield Classic         150000  2018      12000
3           Yamaha Fazer FI          65000  2015      23000
4     Yamaha SZ [2013-2014]          20000  2011      21000
...                     ...            ...   ...        ...
1056              Activa 3g          17000  2010     500000
1057       Honda CB twister          16000  2012      33000
1058     Bajaj Discover 125          15000  2013      35000
1059         Honda CB Shine          12000  2009      53000
1060       Bajaj Pulsar 150          10000  2008      92233

[1061 rows x 4 columns]

In [54]:
data.to_csv('Cleaned_Data.csv')

In [55]:
X = data.drop(columns='selling_price')
y = data['selling_price']

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2)

In [57]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer, ColumnTransformer
from sklearn.pipeline import make_pipeline

In [58]:
ohe = OneHotEncoder()

In [59]:
ohe.fit(X[['name']])

OneHotEncoder()

In [60]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_), ['name']),
                                       remainder = 'passthrough')

In [61]:
lr = LinearRegression()

In [63]:
pipe = make_pipeline(column_trans, lr)

In [64]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Activa 3g', 'Activa 4g', 'Aprilia SR 125', 'BMW G310GS',
       'Bajaj  ct', 'Bajaj Avenger 150', 'Bajaj Avenger 220',
       'Bajaj Avenger Cruise', 'Bajaj Avenger Street',
       'Bajaj Avenger [2015]', 'Bajaj Boxer', 'Bajaj CT 100',
       'Bajaj CT 110', 'Bajaj Disc...
       'Yamaha Fazer ', 'Yamaha Fazer 25', 'Yamaha Fazer Dlx',
       'Yamaha Fazer FI', 'Yamaha Fazer [2009-2016]', 'Yamaha Gladiator',
       'Yamaha RX135', 'Yamaha RXG', 'Yamaha Ray Z', 'Yamaha Rx',
       'Yamaha SZ RR', 'Yamaha SZ X', 'Yamaha SZ [2013-2014]',
       'Yamaha SZ-S', 'Yamaha Saluto', 'Yamaha Saluto RX',
       'Yamaha YBR 125', 'Yamaha YZF R15', 'Yamaha YZF R3', 'Yo Style'],
      dtype=object)]),
                                                  ['name

In [65]:
y_pred = pipe.predict(X_test)

In [66]:
r2_score(y_test, y_pred)

0.7081355652526464

In [67]:
scores = []
for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append(r2_score(y_test, y_pred))

np.argmax(scores)

37

In [68]:
scores[np.argmax(scores)]

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state = np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test, y_pred)

0.8556817453865823

In [69]:
import pickle
pickle.dump(pipe, open('priceprediction.pkl', 'wb'))

In [74]:
pipe.predict(pd.DataFrame([['Yamaha FZ S', 2013, 75000]], columns = ['name', 'year', 'km_driven' ]))

array([44434.94648611])

In [44]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),['name'])],remainder='passthrough')

In [45]:
X = ct.fit_transform(X)

In [47]:
X

<1061x218 sparse matrix of type '<class 'numpy.float64'>'
	with 3183 stored elements in Compressed Sparse Row format>

In [25]:
X = np.array(column_trans.fit_transform(X))

In [27]:
X

array(<1061x218 sparse matrix of type '<class 'numpy.float64'>'
	with 3183 stored elements in Compressed Sparse Row format>, dtype=object)

In [50]:
y_pred  =  lr.predict(X_test)

In [52]:
y_pred

array([ 39739.90023153, 113586.60433803,  46542.12712454,  46835.52786137,
        74467.14228881,  48775.0201016 ,  47996.78922569,  38453.73066922,
        38167.83406118,  39739.90023153,  81982.98938213,  42249.10237326,
        31473.97301938,  28527.72757662,  13004.94759358,  52046.53944328,
        59847.69009492,  61613.08211026,  27491.62547141,  34462.41180471,
        34545.141074  , 152377.01371073,  68153.62436631,  74384.3595152 ,
        45408.60933401,  42626.39774486,  22540.26074275,  16862.76784235,
        89380.76264248,  89216.8197383 ,  25088.97065493,  83539.20653869,
        31875.27619899,  55259.49232405,  74759.90947002, 134559.67425638,
       140318.62374529,  25124.55394303,  54254.32333434,  32194.19314441,
        75804.73077208,  63354.80239602,  50196.45760868,  89206.60261197,
        19759.43279784,  36375.63365606,  39961.77938597,  20477.70712661,
        16960.79799423,  77282.30874493, 129400.14993149,  35885.46377015,
       132040.49526483,  

In [53]:
from sklearn.model_selection import cross_val_score
accur = cross_val_score(estimator = lr, X = X_train, y = y_train)
print("Accuracy: {:.2f} %".format(accur.mean()*100))
print("Standard Deviation: {:.2f} %".format(accur.std()*100))

Accuracy: 53.86 %
Standard Deviation: 15.12 %
